NLS
git-svn-id: file:///home/dev/cadtools@48 ee282334-7117-dc11-a005-000e0ca76e53

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -13,7 +13,7 @@ C_NO_SECURE_WARNINGS()
 #C_FATAL_WARNINGS()
 
 HDEFINE(VERSION, "01112008")
-HDEFINE(RELEASE, "Le Visage du Bouc dans le Miroir")
+HDEFINE(RELEASE, "Face of the Goat in the Mirror")
 
 CHECK(cc)
 CHECK(agar, 1.3)
@@ -58,4 +58,16 @@ if [ "${enable_warnings}" = "yes" ]; then
 fi
 if [ "${enable_static}" = "yes" ]; then
 	MDEFINE(LDFLAGS, "-static")
+fi
+
+# Enable NLS if requested explicitely.
+if [ "${enable_nls}" = "yes" ]; then
+	CHECK(gettext)
+	if [ "${HAVE_GETTEXT}" != "yes" ]; then
+		echo "*"
+		echo "* --enable-nls was given but gettext was not found. Try"
+		echo "* running configure again without this option."
+		echo "*"
+		exit 1
+	fi
 fi
