regen
git-svn-id: file:///home/dev/cadtools@7 ee282334-7117-dc11-a005-000e0ca76e53

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,7 +6,7 @@
 # To regenerate this file, get the latest BSDbuild release from
 # http://hypertriton.com/bsdbuild/, and use the command:
 #
-#      configure.in | mkconfigure > configure
+#     $ cat configure.in | mkconfigure > configure
 #
 # Copyright (c) 2001-2007 Hypertriton, Inc. <http://hypertriton.com/>
 # All rights reserved.
@@ -60,7 +60,7 @@ do
 	--enable-*)
 	    option=`echo $arg | sed -e 's/--enable-//' -e 's/=.*//'`
 	    option=`echo $option | sed 's/-/_/g'`
-	    case "$option" in
+	    case "$arg" in
 	        *=*)
 	            eval "enable_${option}='$optarg'"
 		    ;;
@@ -77,7 +77,7 @@ do
 	--with-*)
 	    option=`echo $arg | sed -e 's/--with-//' -e 's/=.*//'`
 	    option=`echo $option | sed 's/-/_/g'`
-	    case "$option" in
+	    case "$arg" in
 	        *=*)
 	            eval "with_${option}='$optarg'"
 		    ;;
@@ -131,6 +131,7 @@ echo "    --srcdir                       Source tree for concurrent build [.]"
 echo "    --help                         Display this message"
 echo "    --enable-nls                   Native Language Support [no]"
 echo "    --with-gettext                 Use gettext tools (msgmerge, ...) [check]"
+echo "    --with-libtool                 Specify path to libtool [check]"
 echo "    --with-manpages                Manual pages (-mdoc) [yes]"
 echo "    --with-docs                    Printable docs (-me/tbl/eqn/pic/refer) [no]"
 echo "    --enable-debug                 Include debugging code [no]"
@@ -140,15 +141,19 @@ exit 1
 fi
 
 MACHINE=`uname -m 2>/dev/null` || MACHINE=unknown
-RELEASE=`uname -r 2>/dev/null` || RELEASE=unknown
+OSRELEASE=`uname -r 2>/dev/null` || OSRELEASE=unknown
 SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
-HOST="$SYSTEM-$RELEASE-$MACHINE"
+HOST="$SYSTEM-$OSRELEASE-$MACHINE"
 echo "Host: $HOST"
 
 echo "# File generated by configure script (BSDbuild 2.1)." > Makefile.config
 echo "Machine: $MACHINE" > config.log
-echo "Release: $RELEASE" >> config.log
+echo "Release: $OSRELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
+for arg
+do
+	echo "Argument: $arg" >> config.log
+done
 mkdir config 1>/dev/null 2>&1
 
 HAVE_MANDOC="no"
@@ -218,6 +223,43 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
+echo -n "checking for libtool..."
+LIBTOOL_BUNDLED="no"
+if [ "${with_libtool}" != "" ]; then
+	LIBTOOL=${with_libtool}
+else
+	ltool=""
+	for path in `echo $PATH | sed 's/:/ /g'`; do
+		if [ -x "${path}/libtool" ]; then
+			ltool=${path}/libtool
+		fi
+	done
+	if [ "${ltool}" != "" ]; then
+		${ltool} --version 1>/dev/null 2>&1
+		if [ $? == 0 ]; then
+			LIBTOOL=${ltool}
+		else
+			LIBTOOL=\${TOP}/mk/libtool/libtool
+			LIBTOOL_BUNDLED="yes"
+		fi
+	else
+		LIBTOOL=\${TOP}/mk/libtool/libtool
+		LIBTOOL_BUNDLED="yes"
+	fi
+fi
+if [ "${LIBTOOL_BUNDLED}" = "yes" ]; then
+	echo "yes (bundled)"
+else
+	grep ^VERSION=1.5 "${LIBTOOL}" 1>/dev/null 2>&1
+	if [ $? == 0 ]; then
+		echo "yes (GNU libtool 1.5)"
+		echo "LIBTOOLFLAGS=-prefer-pic" >> Makefile.config
+	else
+		echo "yes (GNU libtool)"
+	fi
+fi
+echo "LIBTOOL=${LIBTOOL}" >> Makefile.config
+
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
@@ -267,11 +309,11 @@ fi
 
 VERSION="\"06112007\""
 echo "#ifndef VERSION" > config/version.h
-echo "#define VERSION" $VERSION >> config/version.h
+echo "#define VERSION \"$VERSION\"" >> config/version.h
 echo "#endif" >> config/version.h
 RELEASE="\"Worlds of Glass\""
 echo "#ifndef RELEASE" > config/release.h
-echo "#define RELEASE" $RELEASE >> config/release.h
+echo "#define RELEASE \"$RELEASE\"" >> config/release.h
 echo "#endif" >> config/release.h
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
@@ -479,6 +521,72 @@ HAVE_NONNULL_ATTRIBUTE="no"
 echo "HAVE_NONNULL_ATTRIBUTE=$HAVE_NONNULL_ATTRIBUTE" >> Makefile.config
 echo "#undef HAVE_NONNULL_ATTRIBUTE" > config/have_nonnull_attribute.h
 fi;
+echo -n "checking __aligned__ attribute..."
+echo -n "checking __aligned__ attribute..." >> config.log
+cat << EOT > conftest.c
+int main(int argc, char *argv[])
+{
+	struct s1 { int x,y,z; } __attribute__ ((aligned(16)));
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_ALIGNED_ATTRIBUTE="yes"
+echo "HAVE_ALIGNED_ATTRIBUTE=$HAVE_ALIGNED_ATTRIBUTE" >> Makefile.config
+echo "#ifndef HAVE_ALIGNED_ATTRIBUTE" > config/have_aligned_attribute.h
+echo "#define HAVE_ALIGNED_ATTRIBUTE \"$HAVE_ALIGNED_ATTRIBUTE\"" >> config/have_aligned_attribute.h
+echo "#endif" >> config/have_aligned_attribute.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_ALIGNED_ATTRIBUTE="no"
+echo "HAVE_ALIGNED_ATTRIBUTE=$HAVE_ALIGNED_ATTRIBUTE" >> Makefile.config
+echo "#undef HAVE_ALIGNED_ATTRIBUTE" > config/have_aligned_attribute.h
+fi;
+echo -n "checking __packed__ attribute..."
+echo -n "checking __packed__ attribute..." >> config.log
+cat << EOT > conftest.c
+int main(int argc, char *argv[])
+{
+	struct s1 { char c; int x,y,z; } __attribute__ ((packed));
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_PACKED_ATTRIBUTE="yes"
+echo "HAVE_PACKED_ATTRIBUTE=$HAVE_PACKED_ATTRIBUTE" >> Makefile.config
+echo "#ifndef HAVE_PACKED_ATTRIBUTE" > config/have_packed_attribute.h
+echo "#define HAVE_PACKED_ATTRIBUTE \"$HAVE_PACKED_ATTRIBUTE\"" >> config/have_packed_attribute.h
+echo "#endif" >> config/have_packed_attribute.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_PACKED_ATTRIBUTE="no"
+echo "HAVE_PACKED_ATTRIBUTE=$HAVE_PACKED_ATTRIBUTE" >> Makefile.config
+echo "#undef HAVE_PACKED_ATTRIBUTE" > config/have_packed_attribute.h
+fi;
 echo -n "checking for long double..."
 echo -n "checking for long double..." >> config.log
 cat << EOT > conftest.c
@@ -501,19 +609,53 @@ if [ $? != 0 ]; then
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "ok" >> config.log
-	echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
-echo "#define HAVE_LONG_DOUBLE" $HAVE_LONG_DOUBLE >> config/have_long_double.h
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_DOUBLE="yes"
+echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "#define HAVE_LONG_DOUBLE \"$HAVE_LONG_DOUBLE\"" >> config/have_long_double.h
 echo "#endif" >> config/have_long_double.h
-
-	HAVE_LONG_DOUBLE="yes"
-	echo "yes"
 else
-    echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_DOUBLE="no"
+echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+fi;
+echo -n "checking for long long..."
+echo -n "checking for long long..." >> config.log
+cat << EOT > conftest.c
+int
+main(int argc, char *argv[])
+{
+	long long ll = 0.0;
+	unsigned long long ull = 0.0;
+	ll = 1.0;
+	ull = 1.0;
+	return (0);
+}
 
-	HAVE_LONG_DOUBLE="no"
-	echo "no"
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
 fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_LONG="yes"
+echo "#ifndef HAVE_LONG_LONG" > config/have_long_long.h
+echo "#define HAVE_LONG_LONG \"$HAVE_LONG_LONG\"" >> config/have_long_long.h
+echo "#endif" >> config/have_long_long.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_LONG="no"
+echo "#undef HAVE_LONG_LONG" > config/have_long_long.h
+fi;
 echo -n "checking for cygwin environment..."
 echo -n "checking for cygwin environment..." >> config.log
 cat << EOT > conftest.c
@@ -639,6 +781,7 @@ echo -n "checking whether Agar works..."
 echo -n "checking whether Agar works..." >> config.log
 cat << EOT > conftest.c
 #include <agar/core.h>
+#include <agar/gui.h>
 
 int
 main(int argc, char *argv[])
@@ -724,8 +867,8 @@ int main(int argc, char *argv[]) {
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_SG_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_SG_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_SG_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_SG_LIBS} 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_SG_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_SG_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_SG_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_SG_LIBS} ${AGAR_LIBS} 2>>config.log
 if [ $? == 0 ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -760,6 +903,177 @@ echo "no" >> config.log
 echo "#undef HAVE_AGAR_SG" > config/have_agar_sg.h
 echo "#undef AGAR_SG_CFLAGS" > config/agar_sg_cflags.h
 echo "#undef AGAR_SG_LIBS" > config/agar_sg_libs.h
+fi;
+echo -n "checking for agar-dev (http://hypertriton.com/agar-dev/)..."
+echo -n "checking for agar-dev (http://hypertriton.com/agar-dev/)..." >> config.log
+AGAR_VERSION=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-config" ]; then
+		AGAR_VERSION=`${path}/agar-config --version`
+	fi
+done
+AGAR_DEV_VERSION=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-dev-config" ]; then
+		AGAR_DEV_VERSION=`${path}/agar-dev-config --version`
+	fi
+done
+if [ "${AGAR_VERSION}" != "" -a "${AGAR_DEV_VERSION}" != "" ]; then
+echo "yes"
+echo "yes" >> config.log
+echo -n "checking whether agar-dev works..."
+echo -n "checking whether agar-dev works..." >> config.log
+AGAR_CFLAGS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-config" ]; then
+		AGAR_CFLAGS=`${path}/agar-config --cflags`
+	fi
+done
+AGAR_LIBS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-config" ]; then
+		AGAR_LIBS=`${path}/agar-config --libs`
+	fi
+done
+AGAR_DEV_CFLAGS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-dev-config" ]; then
+		AGAR_DEV_CFLAGS=`${path}/agar-dev-config --cflags`
+	fi
+done
+AGAR_DEV_LIBS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-dev-config" ]; then
+		AGAR_DEV_LIBS=`${path}/agar-dev-config --libs`
+	fi
+done
+cat << EOT > conftest.c
+#include <agar/core.h>
+#include <agar/gui.h>
+#include <agar/dev.h>
+
+int main(int argc, char *argv[]) {
+	AG_Window *win;
+
+	DEV_InitSubsystem(0);
+	win = DEV_Browser();
+	return (0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_DEV_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_DEV_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_DEV_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_DEV_LIBS} ${AGAR_LIBS} 2>>config.log
+if [ $? == 0 ]; then
+echo "yes"
+echo "yes" >> config.log
+compile="ok"
+HAVE_AGAR_DEV="yes"
+echo "HAVE_AGAR_DEV=$HAVE_AGAR_DEV" >> Makefile.config
+echo "#ifndef HAVE_AGAR_DEV" > config/have_agar_dev.h
+echo "#define HAVE_AGAR_DEV \"$HAVE_AGAR_DEV\"" >> config/have_agar_dev.h
+echo "#endif" >> config/have_agar_dev.h
+else
+echo "no"
+echo "no" >> config.log
+compile="failed"
+HAVE_AGAR_DEV="no"
+echo "HAVE_AGAR_DEV=$HAVE_AGAR_DEV" >> Makefile.config
+echo "#undef HAVE_AGAR_DEV" > config/have_agar_dev.h
+fi;
+rm -f conftest conftest.c
+if [ "${HAVE_AGAR_DEV}" != "" ]; then
+echo "AGAR_DEV_CFLAGS=$AGAR_DEV_CFLAGS" >> Makefile.config
+echo "AGAR_DEV_LIBS=$AGAR_DEV_LIBS" >> Makefile.config
+echo "#ifndef AGAR_DEV_CFLAGS" > config/agar_dev_cflags.h
+echo "#define AGAR_DEV_CFLAGS \"$AGAR_DEV_CFLAGS\"" >> config/agar_dev_cflags.h
+echo "#endif" >> config/agar_dev_cflags.h
+echo "#ifndef AGAR_DEV_LIBS" > config/agar_dev_libs.h
+echo "#define AGAR_DEV_LIBS \"$AGAR_DEV_LIBS\"" >> config/agar_dev_libs.h
+echo "#endif" >> config/agar_dev_libs.h
+fi;
+else
+echo "no"
+echo "no" >> config.log
+echo "#undef HAVE_AGAR_DEV" > config/have_agar_dev.h
+echo "#undef AGAR_DEV_CFLAGS" > config/agar_dev_cflags.h
+echo "#undef AGAR_DEV_LIBS" > config/agar_dev_libs.h
+fi;
+echo -n "checking for agar-net (http://hypertriton.com/agar-net/)..."
+echo -n "checking for agar-net (http://hypertriton.com/agar-net/)..." >> config.log
+AGAR_NET_VERSION=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-net-config" ]; then
+		AGAR_NET_VERSION=`${path}/agar-net-config --version`
+	fi
+done
+if [ "${AGAR_NET_VERSION}" != "" ]; then
+echo "yes"
+echo "yes" >> config.log
+AGAR_NET_CFLAGS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-net-config" ]; then
+		AGAR_NET_CFLAGS=`${path}/agar-net-config --cflags`
+	fi
+done
+AGAR_NET_LIBS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-net-config" ]; then
+		AGAR_NET_LIBS=`${path}/agar-net-config --libs`
+	fi
+done
+echo -n "checking whether agar-net works..."
+echo -n "checking whether agar-net works..." >> config.log
+cat << EOT > conftest.c
+#include <agar/core.h>
+#include <agar/net.h>
+
+int main(int argc, char *argv[]) {
+	NC_Session sess;
+	NC_Init(&sess, "foo", "bar");
+	NC_Destroy(&sess);
+	return (0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_NET_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_NET_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_NET_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_NET_LIBS} ${AGAR_LIBS} 2>>config.log
+if [ $? == 0 ]; then
+echo "yes"
+echo "yes" >> config.log
+compile="ok"
+HAVE_AGAR_NET="yes"
+echo "HAVE_AGAR_NET=$HAVE_AGAR_NET" >> Makefile.config
+echo "#ifndef HAVE_AGAR_NET" > config/have_agar_net.h
+echo "#define HAVE_AGAR_NET \"$HAVE_AGAR_NET\"" >> config/have_agar_net.h
+echo "#endif" >> config/have_agar_net.h
+else
+echo "no"
+echo "no" >> config.log
+compile="failed"
+HAVE_AGAR_NET="no"
+echo "HAVE_AGAR_NET=$HAVE_AGAR_NET" >> Makefile.config
+echo "#undef HAVE_AGAR_NET" > config/have_agar_net.h
+fi;
+rm -f conftest conftest.c
+if [ "${HAVE_AGAR_NET}" = "yes" ]; then
+echo "AGAR_NET_CFLAGS=$AGAR_NET_CFLAGS" >> Makefile.config
+echo "AGAR_NET_LIBS=$AGAR_NET_LIBS" >> Makefile.config
+echo "#ifndef AGAR_NET_CFLAGS" > config/agar_net_cflags.h
+echo "#define AGAR_NET_CFLAGS \"$AGAR_NET_CFLAGS\"" >> config/agar_net_cflags.h
+echo "#endif" >> config/agar_net_cflags.h
+echo "#ifndef AGAR_NET_LIBS" > config/agar_net_libs.h
+echo "#define AGAR_NET_LIBS \"$AGAR_NET_LIBS\"" >> config/agar_net_libs.h
+echo "#endif" >> config/agar_net_libs.h
+else
+echo "#undef AGAR_NET_CFLAGS" > config/agar_net_cflags.h
+echo "#undef AGAR_NET_LIBS" > config/agar_net_libs.h
+fi;
+else
+echo "no"
+echo "no" >> config.log
+echo "#undef HAVE_AGAR_NET" > config/have_agar_net.h
+echo "#undef AGAR_NET_CFLAGS" > config/agar_net_cflags.h
+echo "#undef AGAR_NET_LIBS" > config/agar_net_libs.h
 fi;
 echo -n "checking for POSIX threads..."
 echo -n "checking for POSIX threads..." >> config.log
@@ -1012,7 +1326,7 @@ if [ "${HAVE_AGAR}" = "no" ]
  then
 	echo "*"
 	echo "* Agar is not installed on your system. It is required by"
-	echo "* this package. You can download it from http://agar.csoft.org/."
+	echo "* this package. See http://hypertriton.com/agar/"
 	echo "*"
 	exit 1
 fi
@@ -1020,7 +1334,23 @@ if [ "${HAVE_AGAR_SG}" = "no" ]
  then
 	echo "*"
 	echo "* Agar-SG is not installed on your system. It is required by"
-	echo "* this package. You can download it from http://agar-sg.csoft.org/."
+	echo "* this package. See http://hypertriton.com/agar-sg/"
+	echo "*"
+	exit 1
+fi
+if [ "${HAVE_AGAR_DEV}" = "no" ]
+ then
+	echo "*"
+	echo "* Agar-DEV is not installed on your system. It is required by"
+	echo "* this package. See http://hypertriton.com/agar-dev/"
+	echo "*"
+	exit 1
+fi
+if [ "${HAVE_AGAR_NET}" = "no" ]
+ then
+	echo "*"
+	echo "* Agar-Net is not installed on your system. It is required by"
+	echo "* this package. See http://hypertriton.com/agar-net/"
 	echo "*"
 	exit 1
 fi
