require agar-dev and agar-net.
git-svn-id: file:///home/dev/cadtools@8 ee282334-7117-dc11-a005-000e0ca76e53

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -10,19 +10,35 @@ HDEFINE(RELEASE, "\"Worlds of Glass\"")
 CHECK(cc)
 CHECK(agar, 1.3)
 CHECK(agar-sg, 1.3)
+CHECK(agar-dev, 1.3)
+CHECK(agar-net, 1.3)
 CHECK(pthreads)
 
 if [ "${HAVE_AGAR}" = "no" ]; then
 	echo "*"
 	echo "* Agar is not installed on your system. It is required by"
-	echo "* this package. You can download it from http://agar.csoft.org/."
+	echo "* this package. See http://hypertriton.com/agar/"
 	echo "*"
 	exit 1
 fi
 if [ "${HAVE_AGAR_SG}" = "no" ]; then
 	echo "*"
 	echo "* Agar-SG is not installed on your system. It is required by"
-	echo "* this package. You can download it from http://agar-sg.csoft.org/."
+	echo "* this package. See http://hypertriton.com/agar-sg/"
+	echo "*"
+	exit 1
+fi
+if [ "${HAVE_AGAR_DEV}" = "no" ]; then
+	echo "*"
+	echo "* Agar-DEV is not installed on your system. It is required by"
+	echo "* this package. See http://hypertriton.com/agar-dev/"
+	echo "*"
+	exit 1
+fi
+if [ "${HAVE_AGAR_NET}" = "no" ]; then
+	echo "*"
+	echo "* Agar-Net is not installed on your system. It is required by"
+	echo "* this package. See http://hypertriton.com/agar-net/"
 	echo "*"
 	exit 1
 fi
