test for agar-math library
git-svn-id: file:///home/dev/cadtools@51 ee282334-7117-dc11-a005-000e0ca76e53

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -414,8 +414,10 @@ if [ "$CC" = "" ]; then
 	for i in `echo $PATH |sed 's/:/ /g'`; do
 		if [ -x "${i}/cc" ]; then
 			CC="${i}/cc"
+			break
 		elif [ -x "${i}/gcc" ]; then
 			CC="${i}/gcc"
+			break
 		fi
 	done
 	if [ "$CC" = "" ]; then
@@ -836,6 +838,7 @@ AGAR_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_VERSION=`${path}/agar-config --version`
+		break
 	fi
 done
 if [ "${AGAR_VERSION}" != "" ]; then
@@ -845,12 +848,14 @@ AGAR_CFLAGS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_CFLAGS=`${path}/agar-config --cflags`
+		break
 	fi
 done
 AGAR_LIBS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_LIBS=`${path}/agar-config --libs`
+		break
 	fi
 done
 echo "AGAR_CFLAGS=$AGAR_CFLAGS" >>Makefile.config
@@ -914,18 +919,130 @@ echo "#undef HAVE_AGAR" >config/have_agar.h
 echo "hdefs[\"HAVE_AGAR\"] = nil" >>configure.lua
 fi;
 rm -f $testdir/conftest conftest.c
+$ECHO_N "checking for Agar-Math library (http://libagar.org/)..."
+$ECHO_N "checking for Agar-Math library (http://libagar.org/)..." >> config.log
+AGAR_VERSION=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-config" ]; then
+		AGAR_VERSION=`${path}/agar-config --version`
+		break
+	fi
+done
+AGAR_MATH_VERSION=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-math-config" ]; then
+		AGAR_MATH_VERSION=`${path}/agar-math-config --version`
+		break
+	fi
+done
+if [ "${AGAR_VERSION}" != "" -a "${AGAR_MATH_VERSION}" != "" ]; then
+echo "yes"
+echo "yes" >> config.log
+$ECHO_N "checking whether FreeSG works..."
+$ECHO_N "checking whether FreeSG works..." >> config.log
+AGAR_CFLAGS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-config" ]; then
+		AGAR_CFLAGS=`${path}/agar-config --cflags`
+		break
+	fi
+done
+AGAR_LIBS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-config" ]; then
+		AGAR_LIBS=`${path}/agar-config --libs`
+		break
+	fi
+done
+AGAR_MATH_CFLAGS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-math-config" ]; then
+		AGAR_MATH_CFLAGS=`${path}/agar-math-config --cflags`
+		break
+	fi
+done
+AGAR_MATH_LIBS=""
+for path in `echo $PATH | sed 's/:/ /g'`; do
+	if [ -x "${path}/agar-math-config" ]; then
+		AGAR_MATH_LIBS=`${path}/agar-math-config --libs`
+		break
+	fi
+done
+cat << EOT > conftest.c
+#include <agar/core.h>
+#include <agar/math.h>
+int main(int argc, char *argv[]) {
+	M_Matrix *A = M_New(2,2);
+	AG_InitCore("test", 0);
+	M_InitSubsystem();
+	M_SetIdentity(A);
+	AG_Destroy();
+	return (0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_MATH_CFLAGS} ${AGAR_CFLAGS} -o $testdir/conftest conftest.c ${AGAR_MATH_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_MATH_CFLAGS} ${AGAR_CFLAGS} -o $testdir/conftest conftest.c ${AGAR_MATH_LIBS} ${AGAR_LIBS} 2>>config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+compile="ok"
+HAVE_AGAR_MATH="yes"
+echo "HAVE_AGAR_MATH=$HAVE_AGAR_MATH" >>Makefile.config
+echo "mdefs[\"HAVE_AGAR_MATH\"] = \"$HAVE_AGAR_MATH\"" >>configure.lua
+echo "#ifndef HAVE_AGAR_MATH" > config/have_agar_math.h
+echo "#define HAVE_AGAR_MATH \"$HAVE_AGAR_MATH\"" >> config/have_agar_math.h
+echo "#endif" >> config/have_agar_math.h
+echo "hdefs[\"HAVE_AGAR_MATH\"] = \"$HAVE_AGAR_MATH\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+compile="failed"
+HAVE_AGAR_MATH="no"
+echo "HAVE_AGAR_MATH=$HAVE_AGAR_MATH" >>Makefile.config
+echo "mdefs[\"HAVE_AGAR_MATH\"] = \"$HAVE_AGAR_MATH\"" >>configure.lua
+echo "#undef HAVE_AGAR_MATH" >config/have_agar_math.h
+echo "hdefs[\"HAVE_AGAR_MATH\"] = nil" >>configure.lua
+fi;
+rm -f $testdir/conftest conftest.c
+if [ "${HAVE_AGAR_MATH}" != "" ]; then
+echo "AGAR_MATH_CFLAGS=$AGAR_MATH_CFLAGS" >>Makefile.config
+echo "mdefs[\"AGAR_MATH_CFLAGS\"] = \"$AGAR_MATH_CFLAGS\"" >>configure.lua
+echo "AGAR_MATH_LIBS=$AGAR_MATH_LIBS" >>Makefile.config
+echo "mdefs[\"AGAR_MATH_LIBS\"] = \"$AGAR_MATH_LIBS\"" >>configure.lua
+echo "#ifndef AGAR_MATH_CFLAGS" > config/agar_math_cflags.h
+echo "#define AGAR_MATH_CFLAGS \"$AGAR_MATH_CFLAGS\"" >> config/agar_math_cflags.h
+echo "#endif" >> config/agar_math_cflags.h
+echo "hdefs[\"AGAR_MATH_CFLAGS\"] = \"$AGAR_MATH_CFLAGS\"" >>configure.lua
+echo "#ifndef AGAR_MATH_LIBS" > config/agar_math_libs.h
+echo "#define AGAR_MATH_LIBS \"$AGAR_MATH_LIBS\"" >> config/agar_math_libs.h
+echo "#endif" >> config/agar_math_libs.h
+echo "hdefs[\"AGAR_MATH_LIBS\"] = \"$AGAR_MATH_LIBS\"" >>configure.lua
+fi;
+else
+echo "no"
+echo "no" >> config.log
+echo "#undef HAVE_AGAR_MATH" >config/have_agar_math.h
+echo "hdefs[\"HAVE_AGAR_MATH\"] = nil" >>configure.lua
+echo "#undef AGAR_MATH_CFLAGS" >config/agar_math_cflags.h
+echo "hdefs[\"AGAR_MATH_CFLAGS\"] = nil" >>configure.lua
+echo "#undef AGAR_MATH_LIBS" >config/agar_math_libs.h
+echo "hdefs[\"AGAR_MATH_LIBS\"] = nil" >>configure.lua
+fi;
 $ECHO_N "checking for agar-dev (http://hypertriton.com/agar-dev/)..."
 $ECHO_N "checking for agar-dev (http://hypertriton.com/agar-dev/)..." >> config.log
 AGAR_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_VERSION=`${path}/agar-config --version`
+		break
 	fi
 done
 AGAR_DEV_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-dev-config" ]; then
 		AGAR_DEV_VERSION=`${path}/agar-dev-config --version`
+		break
 	fi
 done
 if [ "${AGAR_VERSION}" != "" -a "${AGAR_DEV_VERSION}" != "" ]; then
@@ -937,24 +1054,28 @@ AGAR_CFLAGS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_CFLAGS=`${path}/agar-config --cflags`
+		break
 	fi
 done
 AGAR_LIBS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_LIBS=`${path}/agar-config --libs`
+		break
 	fi
 done
 AGAR_DEV_CFLAGS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-dev-config" ]; then
 		AGAR_DEV_CFLAGS=`${path}/agar-dev-config --cflags`
+		break
 	fi
 done
 AGAR_DEV_LIBS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-dev-config" ]; then
 		AGAR_DEV_LIBS=`${path}/agar-dev-config --libs`
+		break
 	fi
 done
 cat << EOT > conftest.c
@@ -1028,6 +1149,7 @@ AGAR_NET_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-net-config" ]; then
 		AGAR_NET_VERSION=`${path}/agar-net-config --version`
+		break
 	fi
 done
 if [ "${AGAR_NET_VERSION}" != "" ]; then
@@ -1037,12 +1159,14 @@ AGAR_NET_CFLAGS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-net-config" ]; then
 		AGAR_NET_CFLAGS=`${path}/agar-net-config --cflags`
+		break
 	fi
 done
 AGAR_NET_LIBS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-net-config" ]; then
 		AGAR_NET_LIBS=`${path}/agar-net-config --libs`
+		break
 	fi
 done
 $ECHO_N "checking whether agar-net works..."
@@ -1118,12 +1242,14 @@ AGAR_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_VERSION=`${path}/agar-config --version`
+		break
 	fi
 done
 FREESG_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/freesg-config" ]; then
 		FREESG_VERSION=`${path}/freesg-config --version`
+		break
 	fi
 done
 if [ "${AGAR_VERSION}" != "" -a "${FREESG_VERSION}" != "" ]; then
@@ -1135,28 +1261,33 @@ AGAR_CFLAGS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_CFLAGS=`${path}/agar-config --cflags`
+		break
 	fi
 done
 AGAR_LIBS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
 		AGAR_LIBS=`${path}/agar-config --libs`
+		break
 	fi
 done
 FREESG_CFLAGS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/freesg-config" ]; then
 		FREESG_CFLAGS=`${path}/freesg-config --cflags`
+		break
 	fi
 done
 FREESG_LIBS=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/freesg-config" ]; then
 		FREESG_LIBS=`${path}/freesg-config --libs`
+		break
 	fi
 done
 cat << EOT > conftest.c
 #include <agar/core.h>
+#include <agar/gui.h>
 #include <freesg/sg.h>
 int main(int argc, char *argv[]) {
 	SG *sg;
@@ -1218,6 +1349,42 @@ $ECHO_N "checking for POSIX threads..."
 $ECHO_N "checking for POSIX threads..." >> config.log
 PTHREADS_CFLAGS=""
 PTHREADS_LIBS="-lpthread"
+if [ -f "/usr/include/pthreads/pthread.h" ]; then
+PTHREADS_CFLAGS="-I/usr/include/pthreads"
+fi;
+if [ -f "/usr/local/include/pthread.h" ]; then
+PTHREADS_CFLAGS="-I/usr/local/include"
+fi;
+if [ -f "/usr/local/include/pthreads/pthread.h" ]; then
+PTHREADS_CFLAGS="-I/usr/local/include/pthreads"
+fi;
+if [ -f "/usr/local/lib/libpthread.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthread"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC1.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGC1"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC1d.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGC1d"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE1.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGCE1"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE1d.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGCE1d"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC2.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGC2"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC2d.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGC2d"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE2.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGCE2"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE2d.a" ]; then
+PTHREADS_LIBS="-L/usr/local/lib -lpthreadGCE2d"
+fi;
 cat << EOT > conftest.c
 #include <pthread.h>
 #include <signal.h>
@@ -1235,8 +1402,8 @@ int main(int argc, char *argv[])
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c ${PTHREADS_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c ${PTHREADS_LIBS} 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS ${PTHREADS_CFLAGS} -o $testdir/conftest conftest.c ${PTHREADS_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${PTHREADS_CFLAGS} -o $testdir/conftest conftest.c ${PTHREADS_LIBS} 2>>config.log
 if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -1296,8 +1463,8 @@ int main(int argc, char *argv[])
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c ${PTHREADS_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c ${PTHREADS_LIBS} 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS ${PTHREADS_CFLAGS} -o $testdir/conftest conftest.c ${PTHREADS_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${PTHREADS_CFLAGS} -o $testdir/conftest conftest.c ${PTHREADS_LIBS} 2>>config.log
 if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -1342,10 +1509,55 @@ $ECHO_N "checking for the X/Open Threads Extension..."
 $ECHO_N "checking for the X/Open Threads Extension..." >> config.log
 if [ "${SYSTEM}" = "FreeBSD" ]; then
 PTHREADS_XOPEN_CFLAGS=""
+if [ -f "/usr/include/pthreads/pthread.h" ]; then
+PTHREADS_XOPEN_CFLAGS="-I/usr/include/pthreads"
+fi;
+if [ -f "/usr/local/include/pthread.h" ]; then
+PTHREADS_XOPEN_CFLAGS="-I/usr/local/include"
+fi;
+if [ -f "/usr/local/include/pthreads/pthread.h" ]; then
+PTHREADS_XOPEN_CFLAGS="-I/usr/local/include/pthreads"
+fi;
 else
 PTHREADS_XOPEN_CFLAGS="-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
+if [ -f "/usr/include/pthreads/pthread.h" ]; then
+PTHREADS_XOPEN_CFLAGS="-I/usr/include/pthreads -U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
+fi;
+if [ -f "/usr/local/include/pthread.h" ]; then
+PTHREADS_XOPEN_CFLAGS="-I/usr/local/include -U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
+fi;
+if [ -f "/usr/local/include/pthreads/pthread.h" ]; then
+PTHREADS_XOPEN_CFLAGS="-I/usr/local/include/pthreads -U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
+fi;
 fi;
 PTHREADS_XOPEN_LIBS="-lpthread"
+if [ -f "/usr/local/lib/libpthread.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthread"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC1.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGC1"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC1d.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGC1d"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE1.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGCE1"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE1d.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGCE1d"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC2.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGC2"
+fi;
+if [ -f "/usr/local/lib/libpthreadGC2d.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGC2d"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE2.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGCE2"
+fi;
+if [ -f "/usr/local/lib/libpthreadGCE2d.a" ]; then
+PTHREADS_XOPEN_LIBS="-L/usr/local/lib -lpthreadGCE2d"
+fi;
 cat << EOT > conftest.c
 #include <pthread.h>
 #include <signal.h>
@@ -1553,11 +1765,11 @@ if [ "${HAVE_AGAR}" = "no" ]
 	echo "*"
 	exit 1
 fi
-if [ "${HAVE_FREESG}" = "no" ]
+if [ "${HAVE_AGAR_MATH}" = "no" ]
  then
 	echo "*"
-	echo "* FreeSG is not installed on your system. It is required by"
-	echo "* this package. Download it from http://freesg.org/"
+	echo "* CADTools requires the Agar-Math library. Please recompile."
+	echo "* Agar without --disable-math."
 	echo "*"
 	exit 1
 fi
@@ -1566,6 +1778,14 @@ if [ "${HAVE_AGAR_NET}" = "no" ]
 	echo "*"
 	echo "* CADTools's CAM functionality requires network support."
 	echo "* Please recompile Agar with the --enable-network option."
+	echo "*"
+	exit 1
+fi
+if [ "${HAVE_FREESG}" = "no" ]
+ then
+	echo "*"
+	echo "* FreeSG is not installed on your system. It is required by"
+	echo "* this package. Download it from http://freesg.org/"
 	echo "*"
 	exit 1
 fi
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -17,6 +17,7 @@ HDEFINE(RELEASE, "Face of the Goat in the Mirror")
 
 CHECK(cc)
 CHECK(agar, 1.3)
+CHECK(agar-math, 1.3)
 CHECK(agar-dev, 1.3)
 CHECK(agar-net, 1.3)
 CHECK(freesg, 1.0)
@@ -30,10 +31,10 @@ if [ "${HAVE_AGAR}" = "no" ]; then
 	echo "*"
 	exit 1
 fi
-if [ "${HAVE_FREESG}" = "no" ]; then
+if [ "${HAVE_AGAR_MATH}" = "no" ]; then
 	echo "*"
-	echo "* FreeSG is not installed on your system. It is required by"
-	echo "* this package. Download it from http://freesg.org/"
+	echo "* CADTools requires the Agar-Math library. Please recompile."
+	echo "* Agar without --disable-math."
 	echo "*"
 	exit 1
 fi
@@ -41,6 +42,14 @@ if [ "${HAVE_AGAR_NET}" = "no" ]; then
 	echo "*"
 	echo "* CADTools's CAM functionality requires network support."
 	echo "* Please recompile Agar with the --enable-network option."
+	echo "*"
+	exit 1
+fi
+
+if [ "${HAVE_FREESG}" = "no" ]; then
+	echo "*"
+	echo "* FreeSG is not installed on your system. It is required by"
+	echo "* this package. Download it from http://freesg.org/"
 	echo "*"
 	exit 1
 fi
